DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS visitors;
DROP TABLE IF EXISTS reports;

CREATE TABLE units (
num INT(3),
plate VARCHAR(7),
activated BOOLEAN,
PRIMARY KEY (num) 
);

CREATE TABLE visitors (
id INT NOT NULL AUTO_INCREMENT,
unit_num INT(3),
    FOREIGN KEY (unit_num) 
    REFERENCES units(num)
    ON UPDATE CASCADE ON DELETE RESTRICT,
name VARCHAR(255),
plate VARCHAR(7),
start_time VARCHAR(255),
end_time VARCHAR(255),
removed BOOLEAN,
pin BOOLEAN,
pin_time VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (id)
);


CREATE TABLE reports (
id INT NOT NULL AUTO_INCREMENT,
unit_num INT(3),
    FOREIGN KEY (unit_num) 
    REFERENCES units(num)
    ON UPDATE CASCADE ON DELETE RESTRICT,
created TIMESTAMP DEFAULT NOW(),
subject VARCHAR(255),
message TEXT,
deleted BOOLEAN DEFAULT 0,
PRIMARY KEY (id)
);

